<?php

/**
 * @file
 * Primary module hooks for Islandora HLS module.
 */

/**
 * Implements hook_theme().
 */
function islandora_hls_theme() {
  return [
    'hls_player' => [
      'variables' => [
        'url' => NULL,
        'media_type' => 'video',
        'width' => '100%',
        'height' => 'auto',
        'controls' => TRUE,
        'autoplay' => FALSE,
        'muted' => FALSE,
        'loop' => FALSE,
      ],
    ],
  ];
}
